### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by naka-nana** [naka-nana/protospace-40244#1]
自身のProtoSpaceのURL（本番環境）
https://protospace-40244.onrender.com

**Comment by Akinori0123** [comment]
@naka-nana さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **正しくフォームを入力すると、コメントが投稿できること**
現在コメント投稿を行うとwe're sorry~のエラー画面になりますのでご確認の程お願いいたします。
<img width="940" alt="We_re_sorry__but_something_went_wrong__500_" src="https://github.com/naka-nana/protospace-40244/assets/49008705/a04b3d9b-1a26-49f4-a320-6e488250df87">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by naka-nana** [comment]
修正しました

**Comment by Akinori0123** [comment]
@naka-nana さん、再提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
